POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "Ens",
    "important": true
}

###
GET http://localhost:3001/api/notes

###
DELETE http://localhost:3001/api/notes/2